server:
  port: 82

feign:
  url:
    bank-url: http://localhost:82
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
        loggerLevel: NONE
      bankClient:
        connectTimeout: 1000
        readTimeout: 10000
        loggerLevel: HEADERS