server:
  port: 81

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3005/account?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 3000
            loggerLevel: NONE
          bankClient:
            url: http://localhost:${wiremock.server.port}
            connectTimeout: 1000
            readTimeout: 1000
            loggerLevel: HEADERS
